substitutions:
  _REGION: asia-south1
  _REPOSITORY: redteam-demo-containers
  _UI_IMAGE: redteam-ui
  _API_IMAGE: redteam-api
  _WORKER_IMAGE: redteam-worker
  _TAG: manual

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-api
    args:
      - build
      - -f
      - docker/api.Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_API_IMAGE}:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_API_IMAGE}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-ui
    args:
      - build
      - -f
      - docker/ui.Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_UI_IMAGE}:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_UI_IMAGE}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: build-worker
    args:
      - build
      - -f
      - docker/worker.Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WORKER_IMAGE}:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WORKER_IMAGE}:latest
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_API_IMAGE}:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_API_IMAGE}:latest
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_UI_IMAGE}:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_UI_IMAGE}:latest
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WORKER_IMAGE}:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_WORKER_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
